language: node_js
node_js:
  - node

install: 
  - npm ci

script: 
  - npm lint
  - npm test

 deploy:
  provider: heroku
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

